version: '2'
services:
    takehome-server:
        container_name: takehome
        build:
            dockerfile: Dockerfile
        image: takehome:latest
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge